### ISSUE TITLE
ns_cmdline.c's replace_variable() does not handle out of memory case

### ISSUE THREAD

**Issue by TeroJaasko** [ARMmbed/mbed-client-cli#83]
### Description
- Type: Bug 

---------------------------------------------------------------
## Bug

**mbed-client-cli version**
v0.3.0-42-g169f7dc

**Expected Behavior**
Out of memory is handled gracefully.

**Actual Behavior**
Undefined behavior if memory allocation fails in replace_variable(), ie in https://github.com/ARMmbed/mbed-client-cli/blob/169f7dcc80a7243ae43d3e1600a3ba243d95b2b0/source/ns_cmdline.c#L1407 and https://github.com/ARMmbed/mbed-client-cli/blob/169f7dcc80a7243ae43d3e1600a3ba243d95b2b0/source/ns_cmdline.c#L1410

**Steps to Reproduce**

----------------------------------------------------------------
## Enhancement

**Reason to enhance/problem with existing solution**

**Suggested enhancement**
Check for OOM, replace pointless "MEM_ALLOC(6)" with a "char valueLocal[6]" or something. Shouldn't the max length of output buffer be also 11 for 32b ints, not 6?

**Pros**

**Cons**

-----------------------------------------------------------------

## Question

**How to?**

**Comment by jupe** [comment]
Thanks for reporting, make totally sense. I can create fix for these.
